# coding: utf-8

"""
    NeuroGate API

    Agent-Native AI Gateway API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurogate.neurogate.models.choice import Choice

class TestChoice(unittest.TestCase):
    """Choice unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Choice:
        """Test Choice
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Choice`
        """
        model = Choice()
        if include_optional:
            return Choice(
                message = neurogate.models.message.Message(
                    role = '', 
                    content = '', )
            )
        else:
            return Choice(
        )
        """

    def testChoice(self):
        """Test Choice"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
