# coding: utf-8

"""
    NeuroGate API

    Agent-Native AI Gateway API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurogate.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_chat_completions(self) -> None:
        """Test case for chat_completions

        Send a chat completion request
        """
        pass

    def test_replay_session(self) -> None:
        """Test case for replay_session

        Replay a debug session
        """
        pass


if __name__ == '__main__':
    unittest.main()
