# coding: utf-8

"""
    NeuroGate API

    Agent-Native AI Gateway API

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from neurogate.neurogate.models.chat_response import ChatResponse

class TestChatResponse(unittest.TestCase):
    """ChatResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ChatResponse:
        """Test ChatResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ChatResponse`
        """
        model = ChatResponse()
        if include_optional:
            return ChatResponse(
                id = '',
                choices = [
                    neurogate.models.choice.Choice(
                        message = neurogate.models.message.Message(
                            role = '', 
                            content = '', ), )
                    ]
            )
        else:
            return ChatResponse(
        )
        """

    def testChatResponse(self):
        """Test ChatResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
